using System;
using System.Collections.Generic;
using System.Threading;

namespace DeviceHive.Client
{
    /// <summary>
    /// Declares methods to connect a client with the DeviceHive service.
    /// Using this class, clients can get information about networks and devices, receive notification and send commands.
    /// </summary>
    public interface IClientService
    {
        /// <summary>
        /// Gets a list of networks.
        /// </summary>
        /// <returns>A list of <see cref="Network"/> objects.</returns>
        List<Network> GetNetworks();

        /// <summary>
        /// Gets a list of devices of the specific network.
        /// </summary>
        /// <param name="networkId">Network identifier.</param>
        /// <returns>A list of <see cref="Device"/> objects that belongs to the specified network.</returns>
        List<Device> GetDevices(int networkId);

        /// <summary>
        /// Gets information about device.
        /// </summary>
        /// <param name="deviceId">Device unique identifier.</param>
        /// <returns><see cref="Device"/> object.</returns>
        Device GetDevice(Guid deviceId);

        /// <summary>
        /// Gets a list of equipment in a device class.
        /// </summary>
        /// <param name="deviceClassId">Device class identifier.</param>
        /// <returns>A list of <see cref="Equipment"/> objects for the specified device class.</returns>
        List<Equipment> GetEquipment(int deviceClassId);

        /// <summary>
        /// Gets a list of device equipment states.
        /// These objects provide information about the current state of device equipment.
        /// </summary>
        /// <param name="deviceId">Device unique identifier.</param>
        /// <returns>A list of <see cref="DeviceEquipmentState"/> objects.</returns>
        List<DeviceEquipmentState> GetEquipmentState(Guid deviceId);

        /// <summary>
        /// Gets a list of notifications generated by the device.
        /// </summary>
        /// <param name="deviceId">Device unique identifier.</param>
        /// <param name="start">Notifications start date (inclusive, optional).</param>
        /// <param name="end">Notifications end date (inclusive, optional).</param>
        /// <returns>A list of <see cref="Notification"/> objects.</returns>
        List<Notification> GetNotifications(Guid deviceId, DateTime? start = null, DateTime? end = null);

        /// <summary>
        /// Polls device notification from the service.
        /// This methods blocks the current thread until a new command is received.
        /// </summary>
        /// <param name="deviceId">Device unique identifier.</param>
        /// <param name="timestamp">Last received notification timestamp.</param>
        /// <param name="token">Cancellation token used to cancel the polling operation.</param>
        /// <returns>A list of <see cref="Notification"/> objects.</returns>
        List<Notification> PollNotifications(Guid deviceId, DateTime? timestamp, CancellationToken token);

        /// <summary>
        /// Gets information about a notification generated by the device.
        /// </summary>
        /// <param name="deviceId">Device unique identifier.</param>
        /// <param name="id">Notification identifier.</param>
        /// <returns>The <see cref="Notification"/> object.</returns>
        Notification GetNotification(Guid deviceId, int id);

        /// <summary>
        /// Subscribe to device notifications
        /// </summary>
        /// <param name="deviceIds">List of device unique identifiers. If empty - subscription for all
        /// available devices will be created</param>
        /// <remarks>
        /// Subscription can be removed through <see cref="UnsubscribeFromNotifications"/> method
        /// </remarks>
        void SubscribeToNotifications(params Guid[] deviceIds);

        /// <summary>
        /// Unsubscribe from device notifications
        /// </summary>
        /// <param name="deviceIds">List of device unique identifiers. If empty - subscription for all
        /// available devices will be removed</param>
        void UnsubscribeFromNotifications(params Guid[] deviceIds);

        /// <summary>
        /// Fires when new notification inserted for some active notification subscription.
        /// </summary>
        /// <remarks>
        /// Subscription can be created through <see cref="SubscribeToNotifications"/> method.
        /// </remarks>
        event EventHandler<NotificationEventArgs> NotificationInserted;
            
        /// <summary>
        /// Gets a list of commands sent to the device.
        /// </summary>
        /// <param name="deviceId">Device unique identifier.</param>
        /// <param name="start">Commands start date (inclusive, optional).</param>
        /// <param name="end">Commands end date (inclusive, optional).</param>
        /// <returns>A list of <see cref="Command"/> objects.</returns>
        List<Command> GetCommands(Guid deviceId, DateTime? start = null, DateTime? end = null);

        /// <summary>
        /// Gets information about a command sent to the device.
        /// </summary>
        /// <param name="deviceId">Device unique identifier.</param>
        /// <param name="id">Command identifier.</param>
        /// <returns>The <see cref="Command"/> object.</returns>
        Command GetCommand(Guid deviceId, int id);

        /// <summary>
        /// Sends new command to the device.
        /// </summary>
        /// <param name="deviceId">Device unique identifier.</param>
        /// <param name="command">A <see cref="Command"/> object to be sent.</param>
        /// <returns>The <see cref="Command"/> object with updated identifier and timestamp.</returns>
        Command SendCommand(Guid deviceId, Command command);

        /// <summary>
        /// Waits for a command to be handled by the device.
        /// This methods blocks the current thread until a command is updated on the server by a device.
        /// </summary>
        /// <param name="deviceId">Device unique identifier.</param>
        /// <param name="id">Command identifier.</param>
        /// <param name="token">Cancellation token used to cancel the polling operation.</param>
        /// <returns>The <see cref="Command"/> object with status and result fields.</returns>
        Command WaitCommand(Guid deviceId, int id, CancellationToken token);
    }
}
