#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceHive.DocGenerator.Templates
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Templates\PartialWsService.cshtml"
    using DeviceHive.DocGenerator;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    public partial class PartialWsService : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 4 "..\..\Templates\PartialWsService.cshtml"

    public MetadataService Service { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");


WriteLiteral("\r\n");


WriteLiteral("\r\n\r\n<h1>");


            
            #line 8 "..\..\Templates\PartialWsService.cshtml"
Write(Html.Encode(Service.Name));

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\r\n<p>");


            
            #line 10 "..\..\Templates\PartialWsService.cshtml"
Write(Html.Documentation(Service.Documentation));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n\r\n<h2>WebSocket Handshake URI</h2>\r\n<pre class=\"uri\">GET ");


            
            #line 13 "..\..\Templates\PartialWsService.cshtml"
                Write(Html.Encode(Service.Uri));

            
            #line default
            #line hidden
WriteLiteral("</pre>\r\n\r\n<h2>Messages</h2>\r\n<table>\r\n    <tr>\r\n        <th style=\"width:150px\">M" +
"essage</th>\r\n        <th style=\"width:80px\">Originator</th>\r\n        <th style=\"" +
"width:100px\">Authorization</th>\r\n        <th style=\"width:400px\">Description</th" +
">\r\n    </tr>\r\n");


            
            #line 23 "..\..\Templates\PartialWsService.cshtml"
     foreach (var method in Service.Methods)
    {

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n        <td><a href=\"#WsReference/");


            
            #line 26 "..\..\Templates\PartialWsService.cshtml"
                             Write(Html.Encode(Service.Name));

            
            #line default
            #line hidden
WriteLiteral("/");


            
            #line 26 "..\..\Templates\PartialWsService.cshtml"
                                                        Write(Html.Encode(method.ID()));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 26 "..\..\Templates\PartialWsService.cshtml"
                                                                                   Write(Html.Encode(method.Name));

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n        <td>");


            
            #line 27 "..\..\Templates\PartialWsService.cshtml"
       Write(Html.Encode(method.Originator));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n        <td>");


            
            #line 28 "..\..\Templates\PartialWsService.cshtml"
       Write(Html.Encode(method.Authorization));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n        <td>");


            
            #line 29 "..\..\Templates\PartialWsService.cshtml"
       Write(Html.Documentation(method.Documentation));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n    </tr>\r\n");


            
            #line 31 "..\..\Templates\PartialWsService.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</table>\r\n");


        }
    }
}
#pragma warning restore 1591
