#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceHive.DocGenerator.Templates
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\Templates\PartialApi.cshtml"
    using DeviceHive.API.Models;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Templates\PartialApi.cshtml"
    using DeviceHive.DocGenerator.Templates;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.4.1.0")]
    public partial class PartialApi : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 4 "..\..\Templates\PartialApi.cshtml"

    public Metadata Doc { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");




WriteLiteral("\r\n<div id=\"sidebar\">\r\n    <ul>\r\n        <li><a href=\"#GetStarted\">Get Started</a>" +
"</li>\r\n        <li><a href=\"#Reference\">Reference</a>\r\n            <ul>\r\n");


            
            #line 12 "..\..\Templates\PartialApi.cshtml"
             foreach (var resource in Doc.Resources)
            {

            
            #line default
            #line hidden
WriteLiteral("                <li><a href=\"#Reference/");


            
            #line 14 "..\..\Templates\PartialApi.cshtml"
                                   Write(Html.Encode(resource.Name));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 14 "..\..\Templates\PartialApi.cshtml"
                                                                Write(Html.Encode(resource.Name));

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                    <ul id=\"nav-Reference-");


            
            #line 15 "..\..\Templates\PartialApi.cshtml"
                                     Write(Html.Encode(resource.Name));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n");


            
            #line 16 "..\..\Templates\PartialApi.cshtml"
                     foreach (var method in resource.Methods)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <li><a href=\"#Reference/");


            
            #line 18 "..\..\Templates\PartialApi.cshtml"
                                           Write(Html.Encode(resource.Name));

            
            #line default
            #line hidden
WriteLiteral("/");


            
            #line 18 "..\..\Templates\PartialApi.cshtml"
                                                                       Write(Html.Encode(method.Name));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 18 "..\..\Templates\PartialApi.cshtml"
                                                                                                  Write(Html.Encode(method.Name));

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 19 "..\..\Templates\PartialApi.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    </ul>\r\n                </li>\r\n");


            
            #line 22 "..\..\Templates\PartialApi.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n        </li>\r\n    </ul>\r\n</div>\r\n<div id=\"content\" class=\"col" +
"umn\" role=\"main\">\r\n    <div id=\"GetStarted\">\r\n        ");


            
            #line 29 "..\..\Templates\PartialApi.cshtml"
    Write(new PartialGetStarted().TransformText());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div id=\"Reference\">\r\n        <h1>Reference</h1>\r\n");


            
            #line 33 "..\..\Templates\PartialApi.cshtml"
         foreach (var resource in Doc.Resources)
        {

            
            #line default
            #line hidden
WriteLiteral("            <h2>");


            
            #line 35 "..\..\Templates\PartialApi.cshtml"
           Write(Html.Encode(resource.Name));

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n");



WriteLiteral("            <p>");


            
            #line 36 "..\..\Templates\PartialApi.cshtml"
          Write(Html.Documentation(resource.Documentation));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");



WriteLiteral("            <p>For ");


            
            #line 37 "..\..\Templates\PartialApi.cshtml"
              Write(Html.Encode(resource.Name));

            
            #line default
            #line hidden
WriteLiteral(" resource details, see the <a href=\"#Reference/");


            
            #line 37 "..\..\Templates\PartialApi.cshtml"
                                                                                        Write(Html.Encode(resource.Name));

            
            #line default
            #line hidden
WriteLiteral("\">resource representation</a> page.</p>\r\n");



WriteLiteral(@"            <table>
                <tr>
                    <th style=""width:120px"">Method</th>
                    <th style=""width:150px"">Authorization</th>
                    <th style=""width:300px"">Uri</th>
                    <th style=""width:400px"">Description</th>
                </tr>
");


            
            #line 45 "..\..\Templates\PartialApi.cshtml"
                 foreach (var method in resource.Methods)
                {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td><a href=\"#Reference/");


            
            #line 48 "..\..\Templates\PartialApi.cshtml"
                                       Write(Html.Encode(resource.Name));

            
            #line default
            #line hidden
WriteLiteral("/");


            
            #line 48 "..\..\Templates\PartialApi.cshtml"
                                                                   Write(Html.Encode(method.Name));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 48 "..\..\Templates\PartialApi.cshtml"
                                                                                              Write(Html.Encode(method.Name));

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                    <td>");


            
            #line 49 "..\..\Templates\PartialApi.cshtml"
                   Write(Html.Encode(method.Authorization));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");


            
            #line 50 "..\..\Templates\PartialApi.cshtml"
                   Write(Html.Encode(method.Verb));

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 50 "..\..\Templates\PartialApi.cshtml"
                                             Write(Html.Encode(method.Uri));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");


            
            #line 51 "..\..\Templates\PartialApi.cshtml"
                   Write(Html.Documentation(method.Documentation));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n");


            
            #line 53 "..\..\Templates\PartialApi.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </table>\r\n");


            
            #line 55 "..\..\Templates\PartialApi.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");


            
            #line 57 "..\..\Templates\PartialApi.cshtml"
     foreach (var resource in Doc.Resources)
    {

            
            #line default
            #line hidden
WriteLiteral("    <div id=\"Reference-");


            
            #line 59 "..\..\Templates\PartialApi.cshtml"
                  Write(Html.Encode(resource.Name));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n        ");


            
            #line 60 "..\..\Templates\PartialApi.cshtml"
    Write(new PartialResource{ Resource = resource }.TransformText());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");


            
            #line 62 "..\..\Templates\PartialApi.cshtml"
    foreach (var method in resource.Methods)
    {

            
            #line default
            #line hidden
WriteLiteral("    <div id=\"Reference-");


            
            #line 64 "..\..\Templates\PartialApi.cshtml"
                  Write(Html.Encode(resource.Name));

            
            #line default
            #line hidden
WriteLiteral("-");


            
            #line 64 "..\..\Templates\PartialApi.cshtml"
                                              Write(Html.Encode(method.Name));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n        ");


            
            #line 65 "..\..\Templates\PartialApi.cshtml"
    Write(new PartialMethod{ Resource = resource, Method = method }.TransformText());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");


            
            #line 67 "..\..\Templates\PartialApi.cshtml"
    }
}

            
            #line default
            #line hidden
WriteLiteral(@"</div>
<script type=""text/javascript"">
    jQuery(function () {
        if (""onhashchange"" in window) {
            window.onhashchange = function () {
                navigator.open(window.location.hash);
            }
        }
        else {
            var storedHash = window.location.hash;
            window.setInterval(function () {
                if (window.location.hash != storedHash) {
                    storedHash = window.location.hash;
                    navigator.open(storedHash);
                }
            }, 100);
        }

        var navigator = {
            open: function (hash) {
                hash = hash.replace(/^\#/, """"); if (hash == """") hash = ""GetStarted"";
                jQuery(""#content > div"").hide().filter(""#"" + hash.replace(/\//g, ""-"")).show();
                jQuery(""#sidebar ul[id^='nav-']"").hide();
                var nav = """"; jQuery.each(hash.split(""/""), function (index, value) { nav += ""-"" + value; jQuery(""#nav"" + nav).show(); });
                window.scrollTo(0, 0);
            }
        }

        navigator.open(window.location.hash);
    });
</script>

");


        }
    }
}
#pragma warning restore 1591
