#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceHive.DocGenerator.Templates
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    public partial class PartialGetStarted : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n<h1>Get Started</h1>\r\n\r\n<p>The DeviceHive API is the central part of the fram" +
"ework which allows different components to interact with each other.\r\nThe API pr" +
"ovides access to information about registered components in the system, and allo" +
"ws them to exchange messages in real time.</p>\r\n\r\n<h2>Use Cases</h2>\r\n\r\n<p>There" +
" are three types of consumers of the DeviceHive API, as shown on the diagram bel" +
"ow:</p>\r\n\r\n<img src=\"{image-path}/Images/UseCases.png\" alt=\"Use Cases\" />\r\n\r\n<h3" +
">Device</h3>\r\n<p>Device is a unit that runs microcode, and it communicates with " +
"the API in the following cases:</p>\r\n<ul>\r\n    <li>When started, device register" +
"s within the framework by passing unique identifier, display name and other meta" +
"-information.</li>\r\n    <li>Device sends notifications with an arbitrary content" +
" format to notify other components about the changes in the device\'s environment" +
".</li>\r\n    <li>Device listens for commands issued by other components and execu" +
"tes them in an appropriate way.</li>\r\n</ul>\r\n\r\n<h3>Client</h3>\r\n<p>Client is an " +
"application that is used to monitor and/or control devices.\r\nIt could be a user " +
"interface, or completely automated software that manages the entire device netwo" +
"rk.\r\nClients may invoke the API in the following use cases:</p>\r\n<ul>\r\n    <li>C" +
"lient enumerates all the devices in the network, view their status and other met" +
"a-information.</li>\r\n    <li>Client listens for device notifications and process" +
"es them in an appropriate way.</li>\r\n    <li>Client sends commands to devices to" +
" trigger any logic on the device side.</li>\r\n</ul>\r\n\r\n<h3>Administrator</h3>\r\n<p" +
">Administrator controls all aspects of the environment with the full access to t" +
"he API.\r\nCommonly, administrators will need to use this API in the following cas" +
"es:</p>\r\n<ul>\r\n    <li>Administrator creates and manages API users (clients and " +
"other administrators).</li>\r\n    <li>Administrator creates and manages device ne" +
"tworks and associates users with them.</li>\r\n    <li>Administrator monitors devi" +
"ces and all dispatched notifications and commands.</li>\r\n</ul>\r\n\r\n<h2>Resources<" +
"/h2>\r\n<p>The DeviceHive API is a RESTful service, which operates on several reso" +
"urce types.\r\nThe diagram below reflects all used resource types and their relati" +
"onships:</p>\r\n<img src=\"{image-path}/Images/DataModel.png\" alt=\"Data Model\" />\r\n" +
"<ul>\r\n    <li><a href=\"#Reference/User\">User</a>: represents a user with credent" +
"ials and API access rights (client or administrator).</li>\r\n    <li><a href=\"#Re" +
"ference/Network\">Network</a>: represents an isolation entity that encapsulates m" +
"ultiple devices with controlled access.</li>\r\n    <li><a href=\"#Reference/Device" +
"\">Device</a>: represents a unit that runs microcode.</li>\r\n    <li><a href=\"#Ref" +
"erence/DeviceClass\">Device Class</a>: represents an entity that holds all meta-i" +
"nformation about particular type of devices.</li>\r\n    <li><a href=\"#Reference/E" +
"quipment\">Equipment</a>: represents meta-information about one unit of equipment" +
" devices have onboard.</li>\r\n    <li><a href=\"#Reference/DeviceNotification\">Dev" +
"ice Notification</a>: represents a message dispatched by devices for clients.</l" +
"i>\r\n    <li><a href=\"#Reference/DeviceCommand\">Device Command</a>: represents a " +
"message dispatched by clients for devices.</li>\r\n</ul>\r\n\r\n<h2>Server Processes</" +
"h2>\r\n<p>Besides the CRUD access to all resources listed above, the API includes " +
"several business features implemented on the server side. The sections below pro" +
"vide more information about their implementation.</p>\r\n\r\n<h3>Message routing</h3" +
">\r\n<p>One of the primary features of the service is to connect devices with clie" +
"nts in real-time. This is achieved on the server-side by routing new commands an" +
"d notification to their recipients with minimal delays.</p>\r\n<p>There are three " +
"methods for API clients to receive incoming messages:</p>\r\n<ol>\r\n    <li><strong" +
">Polling</strong>: The client periodically requests the server to retrieve new <" +
"a href=\"#Reference/DeviceCommand/poll\">commands</a> or <a href=\"#Reference/Devic" +
"eNotification/poll\">notifications</a>. The request must include the <em>waitTime" +
"out=0</em> parameter to disable waiting on the server.</li>\r\n    <li><strong>Lon" +
"g Polling</strong>: The client makes request to the server, but the server respo" +
"nds only when a new message is available, or if the waiting timeout is expired (" +
"specified in the <em>waitTimeout</em> parameter). That approach is generally mor" +
"e efficient and minimizes message receive delays.</li>\r\n    <li><strong>WebSocke" +
"t</strong>: A separate WebSocket API allows clients to open persistent connectio" +
"ns with the server, subscribe to particular commands or notifications and then r" +
"eceive messages from the server. The URL of the WebSocket endpoint could be retr" +
"ieved using the <a href=\"#Reference/ApiInfo/get\">ApiInfo: get</a> call.</li>\r\n</" +
"ol>\r\n<p>In all three methods it\'s possible to specify the <em>timestamp</em> par" +
"ameter as starting date/time (non-inclusive) for incoming messages. If that para" +
"meter is omitted, the server\'s current timestamp is taken instead.</p>\r\n<p>In or" +
"der to receive all messages in the right order, the clients should always pass t" +
"he timestamp of the last received message when polling or subscribing. If no mes" +
"sages were ever received, the client should get the server\'s current timestamp u" +
"sing the <a href=\"#Reference/ApiInfo/get\">ApiInfo: get</a> call and use it until" +
" a new message is received.</p>\r\n\r\n<h3>Tracking device equipment state</h3>\r\n<p>" +
"One of the useful features provided by the server is tracking the most recent st" +
"ate of device equipment (e.g. sensors, meters, etc.). The API clients may use th" +
"e <a href=\"#Reference/Device/equipment\">Device: equipment</a> operation to recei" +
"ve the current state of the device equipment.</p>\r\n<p>In order to support that f" +
"unctionality, devices must send properly formatted <a href=\"#Reference/DeviceNot" +
"ification/insert\">notifications</a> about changes in the current equipment state" +
". The notification resource must include the following properties:</p>\r\n<ul>\r\n  " +
"  <li><strong>notification</strong>: Must be \'equipment\'.</li>\r\n    <li><strong>" +
"parameters</strong>: Must be a JSON object with the \'equipment\' property contain" +
"ing the corresponding equipment code. Other properties in the JSON object should" +
" reflect the equipment state.</li>\r\n</ul>\r\n\r\n<h3>Server-originated notifications" +
"</h3>\r\n<p>Devices are not the only source of notifications in the system: the se" +
"rver also generates special notifications about various device events. The list " +
"below includes all such notifications with their description:</p>\r\n<ul>\r\n    <li" +
"><strong>$device-add</strong>: Dispatched once for newly registered device. The " +
"notification includes all device properties specified during registration.</li>\r" +
"\n    <li><strong>$device-update</strong>: Dispatched every time device propertie" +
"s are updated (e.g. device name, status, etc.). The notification includes only t" +
"he changed properties. If no properties were changed, the notification parameter" +
"s property is an empty object.</li>\r\n</ul>\r\n\r\n<h3>Automatic Offline device statu" +
"s</h3>\r\n<p>The server provides a capability to auto-update the device status to " +
"Offline after certain period of inactivity. A device is considered to be inactiv" +
"e when it does not send any notifications for a specified period of time. Please" +
" note the status is not currently reverted to the original value when a device i" +
"s brought back online.</p>\r\n<p>The feature is enabled, if a corresponding <a hre" +
"f=\"#Reference/DeviceClass\">device class</a> includes a positive offlineTimeout p" +
"roperty.</p>\r\n\r\n<h2>Authentication</h2>\r\n<p>The API supports two types of authen" +
"tication: User and Device.</p>\r\n\r\n<h3>User</h3>\r\n<p>The users are authenticated " +
"using <a href=\"http://en.wikipedia.org/wiki/Basic_access_authentication\" target=" +
"\"_blank\">HTTP Basic Authentication</a>.</p>\r\n<p>The access is provided based on " +
"authenticated user role (Client or Administrator), please refer to the <a href=\"" +
"#Reference\">Reference</a> for the list of available resources and methods for ea" +
"ch user role.</p>\r\n\r\n<h3>Device</h3>\r\n<p>Devices are authenticated by passing tw" +
"o custom HTTP headers:</p>\r\n<ul>\r\n    <li><strong>Auth-DeviceID</strong>: Device" +
" unique identifier.</li>\r\n    <li><strong>Auth-DeviceKey</strong>: Device authen" +
"tication key.</li>\r\n</ul>\r\n<p>Both device unique identifier and authentication k" +
"ey are specified during <a href=\"#Reference/Device/register\">device registration" +
"</a>.</p>\r\n\r\n<h2>Response Codes</h2>\r\n<p>The API uses HTTP Status Codes to notif" +
"y clients about the status of requested operation. As usual, the 2xx codes indic" +
"ate the operation has been completed successfully, the 4xx codes indicate client" +
" errors, and 5xx codes reflect server errors.</p>\r\n<p>The list below provides so" +
"me additional information about common status codes returned by API operations:<" +
"/p>\r\n<ul>\r\n    <li><strong>200 OK</strong>: Requested operation completed succes" +
"sfully. The response body includes a resource object as specified in the API ref" +
"erence.</li>\r\n    <li><strong>201 Created</strong>: Requested operation complete" +
"d successfully and a new resource has been created (typically for POST operation" +
"s). The HTTP Location header includes the URL of created resource. The response " +
"body includes created resource object as specified in the API reference.</li>\r\n " +
"   <li><strong>204 No Content</strong>: Requested operation completed successful" +
"ly and there is no resource in the response body (typically for DELETE operation" +
"s).</li>\r\n    <li><strong>400 Bad Request</strong>: The client did not specify a" +
"ll required parameters or some parameters passed are invalid. The response body " +
"includes a JSON object with the \'message\' property describing the error details." +
"</li>\r\n    <li><strong>401 Unauthorized</strong>: The client did not specify aut" +
"hentication headers or access to the requested resource is not allowed for the c" +
"urrent identity. The response body includes a JSON object with the \'message\' pro" +
"perty describing the error details.</li>\r\n    <li><strong>403 Forbidden</strong>" +
": The server could not complete the requested operation with the specified param" +
"eters (e.g. network with such name already exists). The response body includes a" +
" JSON object with the \'message\' property describing the error details.</li>\r\n   " +
" <li><strong>404 Not Found</strong>: The specified resource is not found. The re" +
"sponse body includes a JSON object with the \'message\' property describing the er" +
"ror details.</li>\r\n    <li><strong>405 Method Not Allowed</strong>: The specifie" +
"d operation for the current resource is not allowed. The response body includes " +
"a JSON object with the \'message\' property describing the error details.</li>\r\n  " +
"  <li><strong>500 Internal Server Error</strong>: The server error occurred whil" +
"e processing requested operation. The expected response format is not documented" +
".</li>\r\n</ul>");


        }
    }
}
#pragma warning restore 1591
