#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceHive.DocGenerator.Templates
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class PartialGetStarted : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n<h1>Get Started</h1>\r\n\r\n<p>The DeviceHive API is the central part of the fram" +
"ework which allows different components to interact with each other.\r\nThe API pr" +
"ovides access to information about registered components in the system, and allo" +
"ws them to exchange messages in real time.</p>\r\n\r\n<h2>Use Cases</h2>\r\n\r\n<p>There" +
" are three types of consumers of the DeviceHive API, as shown on the diagram bel" +
"ow:</p>\r\n\r\n<img src=\"{image-path}/Images/UseCases.png\" alt=\"Use Cases\" />\r\n\r\n<h3" +
">Device</h3>\r\n<p>Device is a unit that runs microcode, and it communicates with " +
"the API in the following cases:</p>\r\n<ul>\r\n    <li>When started, device register" +
"s within the framework by passing unique identifier, display name and other meta" +
"-information.</li>\r\n    <li>Device sends notifications with an arbitrary content" +
" format to notify other components about the changes in the device\'s environment" +
".</li>\r\n    <li>Device listens for commands issued by other components and execu" +
"tes them in an appropriate way.</li>\r\n</ul>\r\n\r\n<h3>Client</h3>\r\n<p>Client is an " +
"application that is used to monitor and/or control devices.\r\nIt could be a user " +
"interface, or completely automated software that manages the entire device netwo" +
"rk.\r\nClients may invoke the API in the following use cases:</p>\r\n<ul>\r\n    <li>C" +
"lient enumerates all the devices in the network, view their status and other met" +
"a-information.</li>\r\n    <li>Client listens for device notifications and process" +
"es them in an appropriate way.</li>\r\n    <li>Client sends commands to devices to" +
" trigger any logic on the device side.</li>\r\n</ul>\r\n\r\n<h3>Administrator</h3>\r\n<p" +
">Administrator controls all aspects of the environment with the full access to t" +
"he API.\r\nCommonly, administrators will need to use this API in the following cas" +
"es:</p>\r\n<ul>\r\n    <li>Administrator creates and manages API users and access ke" +
"ys (clients and other administrators).</li>\r\n    <li>Administrator creates and m" +
"anages device networks and associates users with them.</li>\r\n    <li>Administrat" +
"or monitors devices and all dispatched notifications and commands.</li>\r\n</ul>\r\n" +
"\r\n<h2>Resources</h2>\r\n<p>The DeviceHive API is a RESTful service, which operates" +
" on several resource types.\r\nThe diagram below reflects all used resource types " +
"and their relationships:</p>\r\n<img src=\"{image-path}/Images/DataModel.png\" alt=\"" +
"Data Model\" />\r\n<ul>\r\n    <li><a href=\"#Reference/User\">User</a>: represents a u" +
"ser with credentials and API access rights (client or administrator).</li>\r\n    " +
"<li><a href=\"#Reference/Network\">Network</a>: represents an isolation entity tha" +
"t encapsulates multiple devices with controlled access.</li>\r\n    <li><a href=\"#" +
"Reference/Device\">Device</a>: represents a unit that runs microcode.</li>\r\n    <" +
"li><a href=\"#Reference/DeviceClass\">Device Class</a>: represents an entity that " +
"holds all meta-information about particular type of devices.</li>\r\n    <li><a hr" +
"ef=\"#Reference/Equipment\">Equipment</a>: represents meta-information about one u" +
"nit of equipment devices have onboard.</li>\r\n    <li><a href=\"#Reference/DeviceN" +
"otification\">Device Notification</a>: represents a message dispatched by devices" +
" for clients.</li>\r\n    <li><a href=\"#Reference/DeviceCommand\">Device Command</a" +
">: represents a message dispatched by clients for devices.</li>\r\n    <li><a href" +
"=\"#Reference/AccessKey\">Access Key</a>: represents an access key with specific A" +
"PI access rights.</li>\r\n</ul>\r\n\r\n<h2>Server Processes</h2>\r\n<p>Besides the CRUD " +
"access to all resources listed above, the API includes several business features" +
" implemented on the server side. The sections below provide more information abo" +
"ut their implementation.</p>\r\n\r\n<h3>Message routing</h3>\r\n<p>One of the primary " +
"features of the service is to connect devices with clients in real-time. This is" +
" achieved on the server-side by routing new commands and notification to their r" +
"ecipients with minimal delays.</p>\r\n<p>There are three methods for API clients t" +
"o receive incoming messages:</p>\r\n<ol>\r\n    <li><strong>Polling</strong>: The cl" +
"ient periodically requests the server to retrieve new <a href=\"#Reference/Device" +
"Command/poll\">commands</a> or <a href=\"#Reference/DeviceNotification/poll\">notif" +
"ications</a>. The request must include the <em>waitTimeout=0</em> parameter to d" +
"isable waiting on the server.</li>\r\n    <li><strong>Long Polling</strong>: The c" +
"lient makes request to the server, but the server responds only when a new messa" +
"ge is available, or if the waiting timeout is expired (specified in the <em>wait" +
"Timeout</em> parameter). That approach is generally more efficient and minimizes" +
" message receive delays.</li>\r\n    <li><strong>WebSocket</strong>: A separate <a" +
" href=\"#WsReference\">WebSocket API</a> allows clients to open persistent connect" +
"ions with the server, subscribe to particular commands or notifications and then" +
" receive messages from the server. The URL of the WebSocket endpoint could be re" +
"trieved using the <a href=\"#Reference/ApiInfo/get\">ApiInfo: get</a> call.</li>\r\n" +
"</ol>\r\n<p>In all three methods it\'s possible to specify the <em>timestamp</em> p" +
"arameter as starting date/time (non-inclusive) for incoming messages. If that pa" +
"rameter is omitted, the server\'s current timestamp is taken instead.</p>\r\n<p>In " +
"order to receive all messages in the right order, the clients should always pass" +
" the timestamp of the last received message when polling or subscribing. If no m" +
"essages were ever received, the client should get the server\'s current timestamp" +
" using the <a href=\"#Reference/ApiInfo/get\">ApiInfo: get</a> call and use it unt" +
"il a new message is received.</p>\r\n\r\n<h3>Tracking device equipment state</h3>\r\n<" +
"p>One of the useful features provided by the server is tracking the most recent " +
"state of device equipment (e.g. sensors, meters, etc.). The API clients may use " +
"the <a href=\"#Reference/Device/equipment\">Device: equipment</a> operation to rec" +
"eive the current state of the device equipment.</p>\r\n<p>In order to support that" +
" functionality, devices must send properly formatted <a href=\"#Reference/DeviceN" +
"otification/insert\">notifications</a> about changes in the current equipment sta" +
"te. The notification resource must include the following properties:</p>\r\n<ul>\r\n" +
"    <li><strong>notification</strong>: Must be \'equipment\'.</li>\r\n    <li><stron" +
"g>parameters</strong>: Must be a JSON object with the \'equipment\' property conta" +
"ining the corresponding equipment code. Other properties in the JSON object shou" +
"ld reflect the equipment state.</li>\r\n</ul>\r\n\r\n<h3>Server-originated notificatio" +
"ns</h3>\r\n<p>Devices are not the only source of notifications in the system: the " +
"server also generates special notifications about various device events. The lis" +
"t below includes all such notifications with their description:</p>\r\n<ul>\r\n    <" +
"li><strong>$device-add</strong>: Dispatched once for newly registered device. Th" +
"e notification includes all device properties specified during registration.</li" +
">\r\n    <li><strong>$device-update</strong>: Dispatched every time device propert" +
"ies are updated (e.g. device name, status, etc.). The notification includes only" +
" the changed properties. If no properties were changed, the notification paramet" +
"ers property is an empty object.</li>\r\n</ul>\r\n\r\n<h3>Automatic Offline device sta" +
"tus</h3>\r\n<p>The server provides a capability to auto-update the device status t" +
"o Offline after certain period of inactivity. A device is considered to be inact" +
"ive when it is not persistently connected and it does not send any notifications" +
" for a specified period of time. Please note the status is not currently reverte" +
"d to the original value when a device is brought back online.</p>\r\n<p>The featur" +
"e is enabled, if a corresponding <a href=\"#Reference/DeviceClass\">device class</" +
"a> includes a positive offlineTimeout property.</p>\r\n\r\n<h3>Server Extensibility<" +
"/h3>\r\n<p>The DeviceHive allows to extend server logic by implementing the IMessa" +
"geManager interface in a separate plug-in assembly and referencing it from the c" +
"onfiguration file. The plug-ins can inspect all transmitted messages and apply c" +
"ustom logic as necessary.</p>\r\n\r\n<h2>Authentication</h2>\r\n<p>The API supports th" +
"ree types of authentication: User, Access Key and Device.</p>\r\n\r\n<h3>User</h3>\r\n" +
"<p>The users are authenticated using <a href=\"http://en.wikipedia.org/wiki/Basic" +
"_access_authentication\" target=\"_blank\">HTTP Basic Authentication</a>.</p>\r\n<p>T" +
"he access is provided based on authenticated user role (Client or Administrator)" +
", please refer to the <a href=\"#Reference\">Reference</a> for the list of availab" +
"le resources and methods for each user role.</p>\r\n\r\n<h3>Access Key</h3>\r\n<p>Acce" +
"ss key authentication is useful, when third-party applications, clients or devic" +
"es have to access the DeviceHive API. It is possible limit the rights of a parti" +
"cular access key to specific resources and actions, networks, devices, as well a" +
"s restrict usage of the key to a range of source domains and/or IP subnets.</p>\r" +
"\n<p>The access key is passed in the Authorization HTTP header using the Bearer s" +
"cheme as follows:</p>\r\n<ul>\r\n    <li><strong>Authorization</strong>: Bearer &lt;" +
"access_key&gt;</li>\r\n</ul>\r\n\r\n<h3>Device</h3>\r\n<p>Another way how devices could " +
"authenticate themselves is by passing two custom HTTP headers:</p>\r\n<ul>\r\n    <l" +
"i><strong>Auth-DeviceID</strong>: Device unique identifier.</li>\r\n    <li><stron" +
"g>Auth-DeviceKey</strong>: Device authentication key.</li>\r\n</ul>\r\n<p>Both devic" +
"e unique identifier and authentication key are specified during <a href=\"#Refere" +
"nce/Device/register\">device registration</a>.</p>\r\n\r\n<h2>Response Codes</h2>\r\n<p" +
">The API uses HTTP Status Codes to notify clients about the status of requested " +
"operation. As usual, the 2xx codes indicate the operation has been completed suc" +
"cessfully, the 4xx codes indicate client errors, and 5xx codes reflect server er" +
"rors.</p>\r\n<p>The list below provides some additional information about common s" +
"tatus codes returned by API operations:</p>\r\n<ul>\r\n    <li><strong>200 OK</stron" +
"g>: Requested operation completed successfully. The response body includes a res" +
"ource object as specified in the API reference.</li>\r\n    <li><strong>201 Create" +
"d</strong>: Requested operation completed successfully and a new resource has be" +
"en created (typically for POST operations). The HTTP Location header includes th" +
"e URL of created resource. The response body includes created resource object as" +
" specified in the API reference.</li>\r\n    <li><strong>204 No Content</strong>: " +
"Requested operation completed successfully and there is no resource in the respo" +
"nse body (typically for DELETE operations).</li>\r\n    <li><strong>400 Bad Reques" +
"t</strong>: The client did not specify all required parameters or some parameter" +
"s passed are invalid. The response body includes a JSON object with the \'message" +
"\' property describing the error details.</li>\r\n    <li><strong>401 Unauthorized<" +
"/strong>: The client did not specify authentication headers or access to the req" +
"uested resource is not allowed for the current identity. The response body inclu" +
"des a JSON object with the \'message\' property describing the error details.</li>" +
"\r\n    <li><strong>403 Forbidden</strong>: The server could not complete the requ" +
"ested operation with the specified parameters (e.g. network with such name alrea" +
"dy exists). The response body includes a JSON object with the \'message\' property" +
" describing the error details.</li>\r\n    <li><strong>404 Not Found</strong>: The" +
" specified resource is not found. The response body includes a JSON object with " +
"the \'message\' property describing the error details.</li>\r\n    <li><strong>405 M" +
"ethod Not Allowed</strong>: The specified operation for the current resource is " +
"not allowed. The response body includes a JSON object with the \'message\' propert" +
"y describing the error details.</li>\r\n    <li><strong>500 Internal Server Error<" +
"/strong>: The server error occurred while processing requested operation. The ex" +
"pected response format is not documented.</li>\r\n</ul>");


        }
    }
}
#pragma warning restore 1591
