#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceHive.DocGenerator.Templates
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Templates\PartialWsMethod.cshtml"
    using DeviceHive.DocGenerator;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class PartialWsMethod : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 4 "..\..\Templates\PartialWsMethod.cshtml"

    public MetadataService Service { get; set; }
    public MetadataMethod Method { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");


WriteLiteral("\r\n");


WriteLiteral("\r\n\r\n<h1>");


            
            #line 9 "..\..\Templates\PartialWsMethod.cshtml"
Write(Html.Encode(Service.Name));

            
            #line default
            #line hidden
WriteLiteral(": ");


            
            #line 9 "..\..\Templates\PartialWsMethod.cshtml"
                           Write(Html.Encode(Method.Name));

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\r\n<p>");


            
            #line 11 "..\..\Templates\PartialWsMethod.cshtml"
Write(Html.Documentation(Method.Documentation));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n\r\n");


            
            #line 13 "..\..\Templates\PartialWsMethod.cshtml"
 if (Method.Originator != "Server")
{

            
            #line default
            #line hidden
WriteLiteral("<h2>Request Message</h2>\r\n");


            
            #line 16 "..\..\Templates\PartialWsMethod.cshtml"


            
            #line default
            #line hidden
WriteLiteral("<h3>Authorization</h3>\r\n");



WriteLiteral("<p>");


            
            #line 18 "..\..\Templates\PartialWsMethod.cshtml"
Write(Html.Encode(Method.Authorization));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");


            
            #line 19 "..\..\Templates\PartialWsMethod.cshtml"


            
            #line default
            #line hidden
WriteLiteral("<h3>Message Representation</h3>\r\n");


            
            #line 21 "..\..\Templates\PartialWsMethod.cshtml"

            
            #line default
            #line hidden
            
            #line 21 "..\..\Templates\PartialWsMethod.cshtml"
Write(Html.JsonRepresentation(Method.RequestParameters));

            
            #line default
            #line hidden
            
            #line 21 "..\..\Templates\PartialWsMethod.cshtml"
                                                  
    

            
            #line default
            #line hidden
WriteLiteral("<h3>Message Parameters</h3>\r\n");



WriteLiteral("<table>\r\n    <tr>\r\n        <th style=\"width:200px\">Property Name</th>\r\n        <t" +
"h style=\"width:80px\">Required</th>\r\n        <th style=\"width:80px\">Type</th>\r\n  " +
"      <th style=\"width:400px\">Description</th>\r\n    </tr>\r\n");


            
            #line 31 "..\..\Templates\PartialWsMethod.cshtml"
     foreach (var parameter in Method.RequestParameters)
    {

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n        <td>");


            
            #line 34 "..\..\Templates\PartialWsMethod.cshtml"
       Write(Html.Encode(parameter.Name));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n        <td>");


            
            #line 35 "..\..\Templates\PartialWsMethod.cshtml"
        Write(parameter.IsRequred ? "Yes" : "No");

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n        <td>");


            
            #line 36 "..\..\Templates\PartialWsMethod.cshtml"
       Write(Html.Encode(parameter.Type));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n        <td>");


            
            #line 37 "..\..\Templates\PartialWsMethod.cshtml"
       Write(Html.Documentation(parameter.Documentation));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n    </tr>\r\n");


            
            #line 39 "..\..\Templates\PartialWsMethod.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</table>\r\n");


            
            #line 41 "..\..\Templates\PartialWsMethod.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>");


            
            #line 43 "..\..\Templates\PartialWsMethod.cshtml"
Write(Method.Originator == "Client" ? "Response" : "Server");

            
            #line default
            #line hidden
WriteLiteral(" Message</h2>\r\n");


            
            #line 44 "..\..\Templates\PartialWsMethod.cshtml"
 if (Method.ResponseDocumentation != null)
{

            
            #line default
            #line hidden
WriteLiteral("<p>");


            
            #line 46 "..\..\Templates\PartialWsMethod.cshtml"
Write(Html.Documentation(Method.ResponseDocumentation));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");


            
            #line 47 "..\..\Templates\PartialWsMethod.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<h3>Message Representation</h3>\r\n");


            
            #line 50 "..\..\Templates\PartialWsMethod.cshtml"
Write(Html.JsonRepresentation(Method.ResponseParameters));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h3>Message Parameters</h3>\r\n<table>\r\n    <tr>\r\n        <th style=\"width:200p" +
"x\">Property Name</th>\r\n        <th style=\"width:80px\">Type</th>\r\n        <th sty" +
"le=\"width:400px\">Description</th>\r\n    </tr>\r\n");


            
            #line 59 "..\..\Templates\PartialWsMethod.cshtml"
     foreach (var parameter in Method.ResponseParameters)
    {

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n        <td>");


            
            #line 62 "..\..\Templates\PartialWsMethod.cshtml"
       Write(Html.Encode(parameter.Name));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n        <td>");


            
            #line 63 "..\..\Templates\PartialWsMethod.cshtml"
       Write(Html.Encode(parameter.Type));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n        <td>");


            
            #line 64 "..\..\Templates\PartialWsMethod.cshtml"
       Write(Html.Documentation(parameter.Documentation));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n    </tr>\r\n");


            
            #line 66 "..\..\Templates\PartialWsMethod.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</table>\r\n");


        }
    }
}
#pragma warning restore 1591
