#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceHive.DocGenerator.Templates
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.4.1.0")]
    public partial class PartialGetStarted : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n<h1>Get Started</h1>\r\n\r\n<p>The DeviceHive API is the central part of the fram" +
"ework which allows different components to interact with each other.\r\nThe API pr" +
"ovides access to information about registered components in the system, and allo" +
"ws them to exchange messages in real time.</p>\r\n\r\n<h2>Use Cases</h2>\r\n\r\n<p>There" +
" are three types of consumers of the DeviceHive API, as shown on the diagram bel" +
"ow:</p>\r\n\r\n<img src=\"{image-path}/Images/UseCases.png\" alt=\"Use Cases\" />\r\n\r\n<h3" +
">Device</h3>\r\n<p>Device is a unit that runs microcode, and it communicates with " +
"the API for in following cases:</p>\r\n<ul>\r\n    <li>When started, device register" +
"s within the framework by passing unique identifier, display name and other meta" +
"-information.</li>\r\n    <li>Device sends notifications with an arbitrary content" +
" format to notify other components about the changes in the device\'s environment" +
".</li>\r\n    <li>Device listens for commands issued by other components and execu" +
"tes them in an appropriate way.</li>\r\n</ul>\r\n\r\n<h3>Client</h3>\r\n<p>Client is an " +
"application that is used to monitor and/or control devices.\r\nIt could be a user " +
"interface, or completely automated software that manages the entire device netwo" +
"rk.\r\nClients may invoke the API in the following use cases:</p>\r\n<ul>\r\n    <li>C" +
"lient enumerates all the devices in the network, view their status and other met" +
"a-information.</li>\r\n    <li>Client listens for device notifications and process" +
"es them in an appropriate way.</li>\r\n    <li>Client sends commands to devices to" +
" trigger any logic on the device side.</li>\r\n</ul>\r\n\r\n<h3>Administrator</h3>\r\n<p" +
">Administrator controls all aspects of the environment with the full access to t" +
"he API.\r\nCommonly, administrators will need to use this API in the following cas" +
"es:</p>\r\n<ul>\r\n    <li>Administrator creates and manages API users (clients and " +
"other administrators).</li>\r\n    <li>Administrator creates and manages device ne" +
"tworks and associates users with them.</li>\r\n    <li>Administrator monitors devi" +
"ces and all dispatched notifications and commands.</li>\r\n</ul>\r\n\r\n<h2>Resources<" +
"/h2>\r\n<p>The DeviceHive API is a RESTful service, which operates on several reso" +
"urce types.\r\nThe diagram below reflects all used resource types and their relati" +
"onships:</p>\r\n<img src=\"{image-path}/Images/DataModel.png\" alt=\"Data Model\" />\r\n" +
"\r\n<ul>\r\n    <li><a href=\"#Reference/User\">User</a>: represents a user with crede" +
"ntials and API access rights (client or administrator).</li>\r\n    <li><a href=\"#" +
"Reference/Network\">Network</a>: represents an isolation entity that encapsulates" +
" multiple devices with controlled access.</li>\r\n    <li><a href=\"#Reference/Devi" +
"ce\">Device</a>: represents a unit that runs microcode.</li>\r\n    <li><a href=\"#R" +
"eference/DeviceClass\">Device Class</a>: represents an entity that holds all meta" +
"-information about particular type of devices.</li>\r\n    <li><a href=\"#Reference" +
"/Equipment\">Equipment</a>: represents meta-information about one unit of equipme" +
"nt devices have onboard.</li>\r\n    <li><a href=\"#Reference/DeviceNotification\">D" +
"evice Notification</a>: represents a message dispatched by devices for clients.<" +
"/li>\r\n    <li><a href=\"#Reference/DeviceCommand\">Device Command</a>: represents " +
"a message dispatched by clients for devices.</li>\r\n</ul>\r\n\r\n<h2>Authentication</" +
"h2>\r\n<p>The API supports two types of authentication: User and Device.</p>\r\n\r\n<h" +
"3>User</h3>\r\n<p>The users are authenticated using <a href=\"http://en.wikipedia.o" +
"rg/wiki/Basic_access_authentication\" target=\"_blank\">HTTP Basic Authentication</" +
"a>.</p>\r\n<p>The access is provided based on authenticated user role (Client or A" +
"dministrator), please refer to the <a href=\"#Reference\">Reference</a> for the li" +
"st of available resources and methods for each user role.</p>\r\n\r\n<h3>Device</h3>" +
"\r\n<p>Devices are authenticated by passing two custom HTTP headers:</p>\r\n<ul>\r\n  " +
"  <li><strong>Auth-DeviceID</strong>: Device unique identifier.</li>\r\n    <li><s" +
"trong>Auth-DeviceKey</strong>: Device authentication key.</li>\r\n</ul>\r\n<p>Both d" +
"evice unique identifier and authentication key are specified during <a href=\"#Re" +
"ference/Device/register\">device registration</a>.</p>");


        }
    }
}
#pragma warning restore 1591
