// <auto-generated />
namespace DeviceHive.Data.EF.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _91 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_91));
        
        string IMigrationMetadata.Id
        {
            get { return "201310111016567_9.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
