// <auto-generated />
namespace DeviceHive.Data.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class _94 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_94));
        
        string IMigrationMetadata.Id
        {
            get { return "201410130954454_9.4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
