// <auto-generated />
namespace DeviceHive.Data.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _111 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_111));
        
        string IMigrationMetadata.Id
        {
            get { return "201505221137251_11.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
